volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/muslimbot/data/mariadb
  postgres-shared-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/muslimbot/data/postgres
  frappe-sites:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/muslimbot/data/frappe/sites
  frappe-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/muslimbot/data/frappe/logs
  redis-queue-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/muslimbot/data/redis
  n8n-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/muslimbot/data/n8n
  chatwoot-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/muslimbot/data/chatwoot
  muslimbot-kb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/muslimbot/data/kb_data
