name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x' # Or your specific version
          channel: 'stable'

      - name: Install Dependencies
        working-directory: ./erp-flutter
        run: flutter pub get

      - name: Format Code
        working-directory: ./erp-flutter
        run: flutter format --set-exit-if-changed .

      - name: Analyze Code
        working-directory: ./erp-flutter
        run: flutter analyze

      - name: Run Tests
        working-directory: ./erp-flutter
        run: flutter test

      - name: Build APK
        working-directory: ./erp-flutter
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: erp-flutter/build/app/outputs/flutter-apk/app-release.apk
